name: Rocm test 6.2 push action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, rocm-framework-38]

    env:
      ROCM_REPO: "6.2"
      ROCM_VERSION: "6.2.0"
      ROCM_LIB_VERSION: "60200"
      ROCM_PATH: "/opt/rocm-6.2.0"
      IMAGE_TAG: "6.2.0-ub22"
      DOCKERFILE_PATH: "docker/ubuntu22/rocm-6.2/Dockerfile"
      
    steps:
    - name: checkout main branch
      uses: actions/checkout@v4
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: |
          #Build Docker image
          docker build \
            --no-cache \
            --build-arg rocm_repo=${{ env.ROCM_REPO }} \
            --build-arg rocm_version=${{ env.ROCM_VERSION }} \
            --build-arg rocm_lib_version=${{ env.ROCM_LIB_VERSION }} \
            --build-arg rocm_path=${{ env.ROCM_PATH }} \
            --tag nlingamp/rocm:${{ env.IMAGE_TAG }} \
            --file ${{ env.DOCKERFILE_PATH }} \
            .
            
    - name: Push Docker image to Docker Hub
      run: |
        docker push nlingamp/rocm:${{ env.IMAGE_TAG }}
