name: docker-push.yml

on:
  workflow_dispatch:
    inputs:
      ROCM_REPO:
        description: 'rocm repo'
        required: true
        default: "6.1.3"
      ROCM_VERSION:
        description: 'rocm-ver'
        required: true
        default: "6.1.3"
      ROCM_LIB_VERSION:
        description: 'rocm-lib-ver'
        required: true
        default: "60103"
      ROCM_PATH:
        description: 'rocm-path'
        required: true
        default: "/opt/rocm-6.1.3"
      IMAGE_TAG:
        description: 'docker tag'
        required: true
        default: "ROCM-6.1.3"
jobs:
  build:
    runs-on: [self-hosted, rocm-framework-38]

    env:
      DOCKERFILE_PATH: "docker/rocm/ubuntu22/6.0/Dockerfile"
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      run: |
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
          else
            echo "Docker is already installed."
          fi
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: |
          #Building docker image
          docker build \
            --no-cache \
            --build-arg rocm_repo=${{ github.event.inputs.ROCM_REPO }} \
            --build-arg rocm_version=${{ github.event.inputs.ROCM_VERSION }} \
            --build-arg rocm_lib_version=${{ github.event.inputs.ROCM_LIB_VERSION }} \
            --build-arg rocm_path=${{ github.event.inputs.ROCM_PATH }} \
            --tag nlingamp/pt-github:${{ github.event.inputs.IMAGE_TAG }} \
            --file $DOCKERFILE_PATH \
            .
    - name: Push Docker image to Docker Hub
      run: |
        docker push nlingamp/pt-github:${{ github.event.inputs.IMAGE_TAG }}
