name: Hourly changes in MAIN

on:
  schedule:
    # Runs every hour
    - cron: '*/5 * * * *'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch previous commit
        id: fetch-previous
        run: |
          git fetch origin main
          git show --name-only HEAD > previous-state.txt || echo "No previous state file"

      - name: Store current state
        id: store-state
        run: |
          git ls-tree -r HEAD --name-only > current-state.txt
          diff previous-state.txt current-state.txt > changes.diff || true

      - name: Print changes
        run: |
          if [ -s changes.diff ]; then
            echo "Changes detected:"
            cat changes.diff
          else
            echo "No changes detected."
          fi
