name: Convert String to JSON

on:
  workflow_dispatch:
    inputs:
      VERSION_DETAILS:
        description: 'Enter version details as key:value pairs separated by commas (e.g., "mkl:2024.1, python:3.8")'
        required: true
        default: 'mkl:2024.1,python:3.8'
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Convert String to JSON
        run: |
          # Retrieve the input parameter
          version_details="${{ github.event.inputs.VERSION_DETAILS }}"

          # Initialize the JSON string
          json_string="{"

          # Split the input string by commas
          IFS=',' read -r -a pairs <<< "$version_details"

          # Loop through the key-value pairs
          for pair in "${pairs[@]}"; do
            # Split each pair by colon
            IFS=':' read -r key value <<< "$pair"

            # Append to the JSON string
            json_string+="\"$key\": \"$value\", "
          done

          # Remove the trailing comma and space, and close the JSON string
          json_string=$(echo "$json_string" | sed 's/, $//')
          json_string+="}"

          # Print the constructed JSON string
          json_data=$(cat <<EOF
          {
                  "Constructed JSON: $json_string"
          } 
          EOF
          )
          
          # printing output to file
          echo "$json_data" > docker/sample.json
