name: Convert String to JSON

on:
  workflow_dispatch:
    inputs:
      VERSION_DETAILS:
        description: 'Enter version details as key:value pairs separated by commas (e.g., "mkl:2024.1, python:3.8")'
        required: true
        default: 'mkl:2024.1,python:3.8'
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Convert String to JSON
        run: |
          # Retrieve the input parameter
          version_details="${{ github.event.inputs.VERSION_DETAILS }}"

          # Initialize the JSON string
          json_string="{"

          # Split the input string by commas
          IFS=',' read -r -a pairs <<< "$version_details"

          # Loop through the key-value pairs
          for pair in "${pairs[@]}"; do
            # Split each pair by colon
            IFS=':' read -r key value <<< "$pair"

            # Append to the JSON string
            json_string+="\"$key\": \"$value\", "
          done

          # Remove the trailing comma and space, and close the JSON string
          json_string=$(echo "$json_string" | sed 's/, $//')
          json_string+="}"

          # Print the constructed JSON string
          json_data=$(cat <<EOF
          {
                  "Constructed JSON: $json_string"
          } 
          EOF
          )
          
          # printing output to file
          echo "$json_data" > docker/sample.json
          
      # Remove repo
      - name: clean up repo if it exists
        run: |
          cd $GITHUB_WORKSPACE
          pwd
      # Check out repository under $GITHUB_WORKSPACE
      - name: checkout repo
        uses: actions/checkout@v4
      - name: checkout a branch
        run: git checkout -b auto-json-wf-branch main
      - name: git config user github-actions bot
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
      - name: print branch
        run: git branch
      # Run git status
      - name: git status to show new untracked archived files
        run: git status
      # Find untracked files
      - name: git ls-files --others
        run: git ls-files --others --exclude-standard --full-name
      - name: git add untracked files
        run: git add `git ls-files --others --exclude-standard --full-name`
      - name: git status
        run: git status
      - name: git commit
        run: git commit -am"archive json file"
      - name: git push branch
        run: git push --set-upstream origin auto-json-wf-branch
      - name: gh disable prompt
        run: |
          gh config set prompt disabled
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: use gh CLI to submit PR
        run: |
          gh pr create -B main -H auto-json-wf-branch --title 'github-action PR request for archiving JSON file' --body 'github-action PR request for archiving JSON file'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Remove repo
      - name: clean up repo
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf raj-develop
