name: JSON INPUT

on:
  workflow_dispatch:
    inputs:
      SUBMIT_DATE:
        description: "Enter the submit date (YYYY-MM-DDTHH:MM:SS)"
        required: true
        default: '2024-08-16'
        type: string
      # parse string to json string as component: pytorch, version: 1.2
      COMPONENT_VERSION:
        description: 'Enter the component/version'
        required: true
        default: 'pytorch/latest'
        type: string
      #split this url string to two json objects repo:https:github.com/plan commithash:  
      REPO_COMMITHASH:
        description: 'Enter repo URL Commit and split into two parts url and commit id'
        required: true
        default: 'https://github.com/pytorch/pytorch/commit/4eee2e7a6dfbd9caab6a1e59088744ae91f2aa25'
        type: string
      AISW_TEST_TARGET_GOAL:
        description: "Enter the AISW test target goal"
        required: true
        default: '65785'
        type: string
      ROCM_DETAILS:
        description: "Enter rocm_cuda_score/gfxarch/rocm_version/rocm_actual_testcount/rocm_score/"
        required: true
        default: '96.5/mi210/6.2/5545/98.6'
        type: string
      NV_DETAILS:
        description: "Enter string nvarch/cuda_version/cuda_actual_testcount/cuda_score"
        required: true
        default: 'a100/12.1/5678/98.6'
      VERSION_DETAILS:
        description: "Enter json format string key:value key1:value1"
        required: true
        default: 'mkl:2024.1/python:3.8'
        type: string
      ROCM_CUDA_SCORE_DETAILS:
        description: "Enter the ROCm-CUDA score details "
        required: true
        default: 'comment:additinal/string'
        type: string
      ROCM_SCORE_DETAILS:
        description: "Enter the ROCm score details"
        required: true
        default: 'comment:additinal/string'
        type: string
      CUDA_SCORE_DETAILS:
        description: "Enter the CUDA score details"
        required: true
        default: 'comment:additinal/string'
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    env:
      SCHEMA_VERSION: "V4"

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Parse JSON Input
        run: |

          # convert input values to json
          echo "schema_version: "${{ env.SCHEMA_VERSION }}"" >> file1.txt
          echo "submit_date: "${{ github.event.inputs.SUBMIT_DATE }}"" >> file1.txt
          echo "component_version: "${{ github.event.inputs.COMPONENT_VERSION }}"" >> file1.txt
          echo "repo_commithash: ${{ github.event.inputs.REPO_COMMITHASH }}" >> file1.txt
          echo "aisw_test_target_goal: ${{ github.event.inputs.AISW_TEST_TARGET_GOAL }}" >> file1.txt
          echo "rocm_details: ${{ github.event.inputs.ROCM_DETAILS }}" >> file1.txt
          echo "nvidia_details: ${{ github.event.inputs.NV_DETAILS }}" >> file1.txt
          echo "version_details: ${{ github.event.inputs.VERSION_DETAILS }}" >> file1.txt
          echo "rocm_cuda_score_details: ${{ github.event.inputs.ROCM_CUDA_SCORE_DETAILS }}" >> file1.txt
          echo "rocm_score_details: ${{ github.event.inputs.ROCM_SCORE_DETAILS }}" >> file1.txt
          echo "cuda_score_details: ${{ github.event.inputs.CUDA_SCORE_DETAILS }}" >> file1.txt
          
      - name: Read and print file contents
        run: |
          cat file1.txt

          # Print extracted values to logs
          # echo "Schema_version: $schema_version" >> file1.txt
          # echo "Submit Date: $submit_date" >> file1.txt
          # echo "Component_version: $component_version" >> file1.txt
          # echo "Repo_Commithash: $repo_commithash"
          # echo "AISW Test Target Goal: $aisw_test_target_goal" >> file1.txt
          #echo "ROCm CUDA Score: $rocm_details" >> file1.txt
          #echo "Nvida: $nvidia_details" >> file1.txt
          #echo "Version_details: $version_details" >> file1.txt
          #echo "Rocm_cuda_score_details: $rocm_cuda_score_details" >> file1.txt
          #echo "Rocm_score_details: $rocm_score_details" >> file1.txt
          #echo "Cuda_score_details: $cuda_score_details" >> file1.txt

          
          
