# this job is taking json input and printing

name: Process JSON Input

on:
  workflow_dispatch:
    
jobs:
  create-json:
    runs-on: ubuntu-latest

    steps:
      - name: Read and process sample json file
        run: |
          # sample json file loading
          JSON_FILE='sample.json'

          # read the sample json and ouput it
          JSON_STRING=$(cat $JSON_FILE)
          echo "Read JSOn: $JSON_STRING"