name: JSON INPUT

on:
  workflow_dispatch:
    inputs:
      SUBMIT_DATE:
        description: "Enter the submit date (YYYY-MM-DDTHH:MM:SS)"
        required: true
        default: ''
      COMPONENT_VERSION:
        description: 'Enter the component:"", and version: "", '
        required: true
        default: '{}'
      REPO_COMMITHASH:
        description: 'Enter the repo:"", and commithas: "", '
        required: true
        default: ''
      AISW_TEST_TARGET_GOAL:
        description: "Enter the AISW test target goal"
        required: true
        default: '0.00'
      ROCM_DETAILS:
        description: "Enter json format string rocm_cuda_score, gfxarch:, rocm_version:, rocm_actual_testcount:, rocm_score: "
        required: true
        default: '{"rocm_cuda_score" : "98.44", "gfxarch" : "MI250", "rocm_version" : "6.1", "rocm_actual_testcount" : "358763", "rocm_score" : "99.67"}'
      NV_DETAILS:
        description: "Enter json format string nvarch:, cuda_version:, cuda_actual_testcount:, cuda_score:"
        required: true
        default: '{"nvarch" : "A10G", "cuda_version" : "12.1", "cuda_actual_testcount" : "359149", "cuda_score" : "99.77"}'
      VERSION_DETAILS:
        description: "Enter json format string mkl, python"
        required: true
        default: '{"mkl" : "2024.1", "python" : "3.8"}'
      ROCM_CUDA_SCORE_DETAILS:
        description: "Enter the ROCm-CUDA score details"
        required: true
        default: '{"comment" : "Additional explanations:  string"}'
      ROCM_SCORE_DETAILS:
        description: "Enter the ROCm score details"
        required: true
        default: '{"comment" : "Additional explanations:  string"}'
      CUDA_SCORE_DETAILS:
        description: "Enter the CUDA score details"
        required: true
        default: '{"comment" : "Additional explanations:  string"}'


      

jobs:
  process-json:
    runs-on: ubuntu-latest

    env:
      SCHEMA_VERSION: "V4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Parse JSON input
        run: |
          # Read JSON input from the workflow input
          JSON_ROCM_STRING='${{ github.event.inputs.ROCM_DETAILS }}'
          JSON_NV_STRING='${{ github.event.inputs.NV_DETAILS }}'
          JSON_VERSION_STRING='${{ github.event.inputs.VERSION_DETAILS }}'
          JSON_RCS_STRING='${{ github.event.inputs.ROCM_CUDA_SCORE_DETAILS }}'
          JSON_RS_STRING='${{ github.event.inputs.ROCM_SCORE_DETAILS }}'
          JSON_CS_STRING='${{ github.event.inputs.CUDA_SCORE_DETAILS }}'
          
          # json input string
          schema_version="${{ env.SCHEMA_VERSION }}"
          submit_date="${{ github.event.inputs.SUBMIT_DATE }}"
          component="${{ github.event.inputs.COMPONENT }}"
          version="${{ github.event.inputs.VERSION }}"
          repo="${{ github.event.inputs.REPO }}"
          commithash="${{ github.event.inputs.COMMITHASH }}"
          aisw_test_target_goal="${{ github.event.inputs.AISW_TEST_TARGET_GOAL }}"

          # Use jq to parse JSON and extract values
          rocm_cuda_score=$(echo "$JSON_ROCM_STRING" | jq -r '.rocm_cuda_score')
          gfxarch=$(echo "$JSON_ROCM_STRING" | jq -r '.gfxarch')
          rocm_version=$(echo "$JSON_ROCM_STRING" | jq -r '.rocm_version')
          rocm_actual_testcount=$(echo "$JSON_ROCM_STRING" | jq -r '.rocm_actual_testcount')
          rocm_score=$(echo "$JSON_ROCM_STRING" | jq -r '.rocm_score')
          nvarch=$(echo "$JSON_NV_STRING" | jq -r '.nvarch')
          cuda_version=$(echo "$JSON_NV_STRING" | jq -r '.cuda_version')
          cuda_actual_testcount=$(echo "$JSON_NV_STRING" | jq -r '.cuda_actual_testcount')
          cuda_score=$(echo "$JSON_NV_STRING" | jq -r '.cuda_score')
         
          
          # Print extracted values to logs
          echo "Schema_version: $schema_version"
          echo "Submit Date: $submit_date"
          echo "Component: $component"
          echo "Version: $version"
          echo "Repo: $repo"
          echo "Commit Hash: $commithash"
          echo "AISW Test Target Goal: $aisw_test_target_goal"
          echo "ROCm CUDA Score: $rocm_cuda_score"
          echo "GFXARCH: $gfxarch"
          echo "ROCm Version: $rocm_version"
          echo "ROCm Actual Test Count: $rocm_actual_testcount"
          echo "ROCm Score: $rocm_score"
          echo "NVARCH: $nvarch"
          echo "CUDA Version: $cuda_version"
          echo "CUDA Actual Test Count: $cuda_actual_testcount"
          echo "CUDA Score: $cuda_score"
          echo "VERSION_DETAILS: "
          echo "ROCM_CUDA_SCORE_DETAILS:"
          echo "ROCM_SCORE_DETAILS:"
          echo "CUDA_SCORE_DETAILS:"
