# this job is taking json input and printing

name: Process JSON Input

on:
  workflow_dispatch:
    inputs:
      JSON_FILE:
        description: "the path to the json file"
        required: true
        type: string
    
jobs:
  create-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        
      - name: Read and process sample json file
        run: |
          # sample json file loading
          json_file_path='${{ github.event.inputs.JSON_FILE }}'

          # read the sample json and ouput it
          JSON_STRING=$(cat $json_file_path)
          echo "Read JSON: $JSON_STRING"
