name: JSON INPUT 4 yaml

on:
  workflow_dispatch:
    inputs:
      SUBMIT_DATE:
        description: "Enter the submit date (YYYY-MM-DDTHH:MM:SS)"
        required: true
        default: '2024-08-16'
        type: string
      COMPONENT_VERSION:
        description: 'Enter the component/version'
        required: true
        default: 'pytorch/latest'
        type: string 
      REPO_COMMITHASH:
        description: 'Enter repo URL with commithash'
        required: true
        default: 'https://github.com/pytorch/pytorch/commit/4eee2e7a6dfbd9caab6a1e59088744ae91f2aa25'
        type: string
      AISW_TEST_TARGET_GOAL:
        description: "Enter the AISW test target goal"
        required: true
        default: '65785'
        type: string
      ROCM_DETAILS:
        description: "Enter rocm_cuda_score/gfxarch/rocm_version/rocm_actual_testcount/rocm_score/"
        required: true
        default: '96.5/mi210/6.2/5545/98.6'
        type: string
      NV_DETAILS:
        description: "Enter string nvarch/cuda_version/cuda_actual_testcount/cuda_score"
        required: true
        default: 'a100/12.1/5678/98.6'
      VERSION_DETAILS:
        description: "Enter key:value/key2:value2"
        required: true
        default: 'mkl:2024.1/python:3.8'
        type: string
      ROCM_CUDA_SCORE_DETAILS:
        description: "Enter the ROCm-CUDA score details "
        required: true
        default: 'comment:additinal/string'
        type: string
      ROCM_SCORE_DETAILS:
        description: "Enter the ROCm score details"
        required: true
        default: 'comment:additinal/string'
        type: string
      CUDA_SCORE_DETAILS:
        description: "Enter the CUDA score details"
        required: true
        default: 'comment:additinal/string'
        type: string

jobs:
  process-json:
    runs-on: ubuntu-latest

    env:
      SCHEMA_VERSION: "V4"

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Split input string
        run: |

          # Retrieve the input parameters
          schema_version="${{ env.SCHEMA_VERSION }}"
          submit_date="${{ github.event.inputs.SUBMIT_DATE }}"
          component_version="${{ github.event.inputs.COMPONENT_VERSION }}"
          repo_commithash="${{ github.event.inputs.REPO_COMMITHASH }}"
          aisw_test_target_goal="${{ github.event.inputs.AISW_TEST_TARGET_GOAL }}"
          rocm_details="${{ github.event.inputs.ROCM_DETAILS }}"
          nvidia_details="${{ github.event.inputs.NV_DETAILS }}"
          version_details='${{ github.event.inputs.VERSION_DETAILS }}'
          rocm_cuda_score_details='${{ github.event.inputs.ROCM_CUDA_SCORE_DETAILS }}'
          rocm_score_details='${{ github.event.inputs.ROCM_SCORE_DETAILS }}'
          cuda_score_details='${{ github.event.inputs.CUDA_SCORE_DETAILS }}'

          # Split component_version by "/"
          IFS='/' read -r component version <<< "$component_version"
          IFS='/' read -r rocm_cuda_score gfxarch rocm_version rocm_actual_testcount rocm_score <<< "$rocm_details"
          IFS='/' read -r nvarch cuda_version cuda_actual_testcount cuda_score <<< "$nvidia_details"

          #Split repo_commithash by "/commit "
          repo=$(echo "$repo_commithash" | awk -F '/commit/' '{print $1}')
          commithash=$(echo "$repo_commithash" | awk -F '/commit/' '{print $2}')
          
      - name: Print the JSON DATA
        run: |
          #Printing the User Input
          echo "\"schema_version\": \"$schema_version\""
          echo "\"submit_date\": \"$submit_date\""
          echo "\"component\": \"$component\""
          echo "\"version\": \"$version\""
          echo "\"repo\" : \"$repo\""
          echo "\"commitHash\": \"$commithash\""
          echo "\"aisw_test_target_goal\": \"$aisw_test_target_goal\""
          echo "\"rocm_cuda_score\": \"$rocm_cuda_score\""
          echo "\"gfxarch\": \"$gfxarch\""
          echo "\"rocm_version\": \"$rocm_version\""
          echo "\"rocm_actual_testcount\": \"$rocm_actual_testcount\""
          echo "\"rocm_score\": \"$rocm_score\""
          echo "\"nvarch\": \"$nvarch\""
          echo "\"cuda_version\": \"$cuda_version\""
          echo "\"cuda_actual_testcountt\": \"$cuda_actual_testcount\""
          echo "\"cuda_score\": \"$cuda_score\""
