name: ping servers
#run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      inventory_path:
        description: 'Path to the inventory file or folder'
        required: true
        default: 'inventory/mi300x'
jobs:
  Ping-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- run: |
             #sudo apt install -y software-properties-common sshpass python3-pip
             #python3 -m pip install virtualenv
             #pip3 install -r requirements.txt
      #- run: |
         #chmod +x venv_setup.sh
         #./venv_setup.sh
      #- run: source venv/bin/activate
      - run: ls -lart 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible 
      
      - name: Ping servers
        id: ping_servers
        run: |
          # Run the Ansible ping module and capture the output
          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $GITHUB_WORKSPACE/$temp_file 
          # || echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
          mv $temp_file $GITHUB_WORKSPACE/ping_results.txt
          cat $GITHUB_WORKSPACE/ping_results.txt

      - name: Process Ping Results
        run: |
          # Check for successful pings and failed pings
          grep 'SUCCESS' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Online"}' > $GITHUB_WORKSPACE/final_results.txt 
          echo "final results"
          cat $GITHUB_WORKSPACE/final_results.txt
          
          grep 'Failed' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Offline"}' >> $GITHUB_WORKSPACE/final_results.txt
          echo "final results-2"
          cat $GITHUB_WORKSPACE/final_results.txt

      - name: Upload Ping Results
        uses: actions/upload-artifact@v3
        with:
          name: ping-results
          path: $GITHUB_WORKSPACE/final_results.txt
          
      - run: cat $GITHUB_WORKSPACE/final_results.txt
