# this workflow take the input file and ping all servers from the file
name: ping servers manually

on: 
  workflow_dispatch:
    inputs:
      inventory_path:
        description: 'Path to the inventory file or folder'
        required: true
        default: 'inventory/mi300x'
jobs:
  Ping-servers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible 

      - name: Ping servers
        id: ping_servers
        run: |
          # Run the Ansible ping module and capture the output directly
          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o 

      - name: Process Ping Results
        run: |
          # Run the Ansible ping module again to process the results
          echo "Processing ping results..."
          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o | \
          awk '/SUCCESS/ {print $1, "Online"}; /Failed/ {print $1, "Offline"}'
