name: ping servers
#run-name: ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      inventory_path:
        description: 'Path to the inventory file or folder'
        required: true
        default: 'inventory/mi300x'
jobs:
  Ping-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ls -lart 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Ping servers
        id: ping_servers
        run: |
          # Run the Ansible ping module and capture the output
          ansible all -i ${{ github.event.inputs.inventory_path }} -m ping -o > $GITHUB_WORKSPACE/ping_results.txt || echo "Ping failed" >> $GITHUB_WORKSPACE/ping_results.txt
          cat $GITHUB_WORKSPACE/ping_results.txt
      - name: Process Ping Results
        run: |
          # Check for successful pings and failed pings
          grep 'SUCCESS' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Online"}' > $GITHUB_WORKSPACE/final_results.txt 
          echo "final results"
          cat $GITHUB_WORKSPACE/final_results.txt
          
          grep 'Failed' $GITHUB_WORKSPACE/ping_results.txt | awk '{print $1, "Offline"}' >> $GITHUB_WORKSPACE/final_results.txt
          echo "final results-2"
          cat $GITHUB_WORKSPACE/final_results.txt
