name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Build the Docker image
      run: | 
        #Genereate unique Tag
        uniquw_tag=$(date +%s)
        #build the docker image
        docker build --no-cache --build-arg rocm_repo=6.0 --build-arg rocm_version=6.0.0 --build-arg rocm_lib_version=60000 --build-arg rocm_path=/opt/rocm-6.0.0 -t amddcgpuce/rocm:6.0.0-ub22 -f rocm.ub22.Dockerfile `pwd` --tag nlingamp/pt-github:${unique_tag} .
   
    - name: Push Docker image to Docker Hub
      run: docker push nlingamp/pt-github:${unique_tag}
