name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      run: |
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
          else
            echo "Docker is already installed."
          fi

    - name: Set up Docker Buildx
      run: |
          # Check if Docker Buildx is installed
          if ! docker buildx version &> /dev/null; then
            echo "Docker Buildx not found. Installing Docker Buildx..."
            mkdir -p ~/.docker/cli-plugins/
            curl -L https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
          else
            echo "Docker Buildx is already installed."
          fi
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and Push the Docker image
      run: | 
        #Genereate unique Tag
        unique_tag=$(date +%Y%m%d%H%M%S)
        
        #build the docker image
        docker buildx build \
          --no-cache \
          --build-arg rocm_repo=6.0 \
          --build-arg rocm_version=6.0.0 \
          --build-arg rocm_lib_version=60000 \
          --build-arg rocm_path=/opt/rocm-6.0.0 \
          --tag amddcgpuce/rocm:6.0.0-ub22 \
          --tag nlingamp/pt-github:${unique_tag} \
          -f rocm.ub22.Dockerfile \
          --push .
   
    #- name: Push Docker image to Docker Hub
    # run: docker push nlingamp/pt-github:${unique_tag}
