name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: | 
        #Genereate unique Tag
        unique_tag=$(date +%Y%m%d%H%M%S)
        
        #build the docker image
        docker buildx build --no-cache --build-arg rocm_repo=6.0 --build-arg rocm_version=6.0.0 --build-arg rocm_lib_version=60000 --build-arg rocm_path=/opt/rocm-6.0.0 -t amddcgpuce/rocm:6.0.0-ub22 -f rocm.ub22.Dockerfile `pwd` --tag nlingamp/pt-github:${unique_tag} .
   
    - name: Push Docker image to Docker Hub
      run: docker push nlingamp/pt-github:${unique_tag}
