name: Rocm-CI-Ub

on:
  workflow_dispatch:
    inputs:
      ROCM_REPO:
        description: 'rocm repo'
        required: true
        default: "6.0"
      ROCM_VERSION:
        description: 'rocm-ver'
        required: true
        default: "6.2"
      ROCM_LIB_VERSION:
        description: 'rocm-lib-ver'
        required: true
        default: "60200"
      ROCM_PATH:
        description: 'rocm-path'
        required: true
        default: "/opt/rocm-6.2"
      ROCM_CI_ARTIFACTORY_BUILD_URL:
        description: 'Url for ci'
        required: true
        default: "https://repo.radeon.com/rocm/apt/.apt_6.2/"
      IMAGE_TAG:
        description: 'docker tag'
        required: false # Allow the user to provide a tag or use the default
        
jobs:
  build:
    runs-on: self-hosted

    env:
      ROCM_REPO: "6.2"
      ROCM_VERSION: "6.2"
      ROCM_LIB_VERSION: "60200"
      ROCM_PATH: "/opt/rocm-6.2"
      ROCM_CI_ARTIFACTORY_BUILD_URL: "https://repo.radeon.com/rocm/apt/.apt_6.2/"
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      run: |
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
          else
            echo "Docker is already installed."
          fi
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      id: set_tag
      run: |
          # creating unique tag and parameterized
          unique_tag=Rocm-CI-6.2-$(date +%Y%m%d%H%M%S)
          
          #Building docker image
          docker build \
            --no-cache \
            --build-arg rocm_repo=${{ env.ROCM_REPO }} \
            --build-arg rocm_version=${{ env.ROCM_VERSION }} \
            --build-arg rocm_lib_version=${{ env.ROCM_LIB_VERSION }} \
            --build-arg rocm_path=${{ env.ROCM_PATH }} \
            --build-arg rocm_ci_artifactory_build_url=${{ env.ROCM_CI_ARTIFACTORY_BUILD_URL }} \
            --tag nlingamp/pt-github:${unique_tag} \
            --file rocm.ci.ub22.Dockerfile \
            .

    - name: Push Docker image to Docker Hub
      run: |
        docker push nlingamp/pt-github:${unique_tag}
