name: Rocm-ub-22-6.0

on:
  workflow_dispatch:
    inputs:
      ROCM_REPO:
        description: 'rocm repo'
        required: true
        default: "6.0"
      ROCM_VERSION:
        description: 'rocm-ver'
        required: true
        default: "6.0.0"
      ROCM_LIB_VERSION:
        description: 'rocm-lib-ver'
        required: true
        default: "60000"
      ROCM_PATH:
        description: 'rocm-path'
        required: true
        default: "/opt/rocm-6.0.0"
      IMAGE_TAG:
        description: 'docker tag'
        required: false # Allow the user to provide a tag or use the default
        
jobs:
  build:
    runs-on: [self-hosted, rocm-framework-38]

    env:
      ROCM_REPO: "6.0"
      ROCM_VERSION: "6.0.0"
      ROCM_LIB_VERSION: "60000"
      ROCM_PATH: "/opt/rocm-6.0.0"
      
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker (if not already installed)
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not found. Installing Docker..."
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update -y
          sudo apt-get install -y docker-ce
        else
          echo "Docker is already installed."
        fi
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      id: set_tag
      env:
          IMAGE_TAG_INPUT: ${{ github.event.inputs.image_tag }}
      run: |
          # creating unique tag and parameterized
          if [ -z "$IMAGE_TAG_INPUT" ]; then
            unique_tag=rocm-ub-22-$(date +%Y%m%d%H%M%S)
          else
            unique_tag="$IMAGE_TAG_INPUT"
          fi
          echo "IMAGE_TAG=${unique_tag}" >> $GITHUB_ENV
          
          #Building docker image
          docker build \
            --no-cache \
            --build-arg rocm_repo=${{ env.ROCM_REPO }} \
            --build-arg rocm_version=${{ env.ROCM_VERSION }} \
            --build-arg rocm_lib_version=${{ env.ROCM_LIB_VERSION }} \
            --build-arg rocm_path=${{ env.ROCM_PATH }} \
            --tag nlingamp/pt-github:${unique_tag} \
            --file rocm.ub22.Dockerfile \
            .
    - name: Push Docker image to Docker Hub
      run: |
        docker push nlingamp/pt-github:${{ env.IMAGE_TAG }}
