name: Hello-world

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps: 
    - name: Print Hello-world
      run: echo "Hello, world"

    - name: Print Hostname
      run: echo "Hostname $HOSTNAME"
      shell: bash
      
    - name: create directory sample
      run: |
       mkdir -p sample
       df -h
