name: Hello-world

on: workflow_dispatch

jobs:
  first-job:
    runs-on: self-hosted

    steps: 
    - name: Print Hello-world
      run: echo "Hello, world"

    - name: Print Hostname
      run: echo "Hostname $HOSTNAME"
      shell: bash
