# Example of using PAT to checkout another repository
name: test repo

on:
  workflow_call:

# The jobs section defines jobs to run. Each job has completion status
jobs:
  # caling test-rocm-stable-docker-mi100-gfx908.yml workflow
  setup-runner:
    uses: RajNagaraju/Raj-Dev/.github/workflows/test-repo1.yml@main
    secrets:
      token: ${{ secrets.RAJ_PAT }}
