name: Pull and test docker image

on:
  workflow_dispatch: 
    inputs:
      DOCKER_CONTAINER:
        description: "Docker-user & reponame"
        required: true 
        default: "nlingamp/rocm"
      IMAGE_TAG:
        description: 'docker tag'
        required: true
        default: "6.2.0-ub22"
 
jobs:
  test:
    runs-on: [self-hosted, rocm-framework-38]

    steps:
    - name: checkout repositery
      uses: actions/checkout@v4

    - name: Pull the docker image
      run: docker pull ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.IMAGE_TAG }}

    - name: Run Docker Container and Execute Commands
      run: |
        docker run --privileged --network=host --ipc=host ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.IMAGE_TAG }} rocm-smi

    - name: Remove Docker Image
      run: |
        # Remove the Docker image
        docker rmi ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.IMAGE_TAG }} || true