name: Pull and test docker image

on:
  workflow_dispatch: 
    inputs:
      DOCKER_CONTAINER:
        description: "Docker-user & reponame"
        required: true 
        default: "nlingamp/rocm"
      DIGEST_OR_IMAGE_TAG:
        description: 'docker tag or diges'
        required: true
        default: "6.2.0-ub22"
 
jobs:
  checkout:
    runs-on: [self-hosted, rocm-framework-38]

    steps:
    - name: checkout repositery
      uses: actions/checkout@v4
 
  #define rocminfo job
  rocm-smi:
    runs-on: [self-hosted, rocm-framework-38]

    steps:
    - name: Run Docker Container and Execute Commands
      run: |
        docker run --rm --privileged --network=host --ipc=host ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.DIGEST_OR_IMAGE_TAG }} rocm-smi
        
  #define rocminfo job
  rocminfo:
    runs-on: [self-hosted, rocm-framework-38]

    steps:      
    - name: Stop and Remove Docker Container
      run: |
        echo Run rocminfo
        echo docker run --rm --privileged --network=host --ipc=host ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.DIGEST_OR_IMAGE_TAG }} rocminfo
        docker run --rm --privileged --network=host --ipc=host ${{ github.event.inputs.DOCKER_CONTAINER }}:${{ github.event.inputs.DIGEST_OR_IMAGE_TAG }} rocminfo