name: Pull and test docker image

on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: [self-hosted, rocm-framework-38]

    steps:
    - name: checkout repositery
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Pull the docker image
      run: docker pull nlingamp/rocm:6.2.0-ub22

    - name: Run Docker Container and Execute Commands
      run: |
        docker run --privileged --network=host --ipc=host nlingamp/rocm:6.2.0-ub22 rocm-smi
